"""Versioned public JSON schemas generated by package code."""

from typing import Any


def canonical_registry_schema() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://registry-align.local/schemas/canonical-registry-1.0.json",
        "title": "Canonical Registry",
        "type": "object",
        "required": ["schema_version", "entries"],
        "properties": {
            "schema_version": {"const": "1.0"},
            "defaults": {
                "type": "object",
                "properties": {"language": {"type": "string", "minLength": 1}},
                "additionalProperties": True,
            },
            "entries": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["id", "audio_path", "transcript"],
                    "properties": {
                        "id": {"type": "string", "minLength": 1},
                        "audio_path": {"type": "string", "minLength": 1},
                        "transcript": {"type": "string", "minLength": 1},
                        "language": {"type": "string", "minLength": 1},
                        "speaker_id": {"type": ["string", "null"]},
                        "metadata": {"type": "object"},
                    },
                    "additionalProperties": True,
                },
            },
        },
        "additionalProperties": True,
    }


def output_schema() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://registry-align.local/schemas/validation-output-1.0.json",
        "title": "Registry Aligner Structured Output",
        "type": "object",
        "required": ["schema_version"],
        "properties": {
            "schema_version": {"const": "1.0"},
            "command": {
                "enum": [
                    "init",
                    "validate",
                    "plan",
                    "doctor",
                    "prepare",
                    "process",
                    "status",
                    "qc",
                    "export",
                ]
            },
            "type": {"enum": ["event", "result"]},
            "status": {"type": "string"},
            "counts": {"type": "object", "additionalProperties": {"type": "integer"}},
            "issues": {"type": "array", "items": {"type": "object"}},
            "entries": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
    }
