"""Public synchronous application API and persistence-independent contracts."""

from application.audio_storage import LocalAudioStorage
from application.contracts import (
    AnnotationQuery,
    AudioStorageHandler,
    AudioVerificationResult,
    CreateRecordingCommand,
    PendingSave,
    Queued,
    RecoveryApplied,
    RecoveryConflict,
    RecoveryEnvelope,
    RecoveryOutbox,
    RecoveryResult,
    ResolvedAudio,
    SaveConflict,
    Saved,
    SaveResult,
    SyncState,
)
from application.edit_session import RecordingEditSession
from application.errors import (
    AnnotationNotFoundError,
    AudioAssetNotFoundError,
    AudioIntegrityError,
    AudioUnavailableError,
    ConceptNotFoundError,
    ConceptNotPinnedError,
    ConcurrentRevisionError,
    DatabaseUnavailableError,
    DuplicateAnnotationError,
    GeometryNotAllowedError,
    GeometryOutOfBoundsError,
    InvalidAnnotationAttributesError,
    InvalidRecoveryEnvelopeError,
    LibraryNotFoundError,
    LibraryVersionInUseError,
    LibraryVersionNotFoundError,
    PendingRecoveryOperationError,
    PersistenceError,
    PersistenceIntegrityError,
    RecordingNotFoundError,
    RecoveryStorageError,
    RevisionNotFoundError,
    SpeakerNotFoundError,
    UnsupportedAudioError,
    WorkbenchError,
)
from application.handlers import LibraryHandler, RecordingHandler, RecoveryHandler, SpeakerHandler
from application.persistence import (
    AudioAssetStore,
    LibraryStore,
    PersistenceStore,
    RecordingStore,
    SpeakerStore,
)
from application.read_models import (
    RecordingRevisionSummary,
    RecordingSummary,
    RecordingWorkspace,
)
from application.recovery import FileRecoveryOutbox
from application.validation import library_content_sha256
from application.workbench import WorkbenchAPI, create_workbench

__all__ = [
    "AnnotationNotFoundError",
    "AnnotationQuery",
    "AudioAssetNotFoundError",
    "AudioAssetStore",
    "AudioIntegrityError",
    "AudioStorageHandler",
    "AudioUnavailableError",
    "AudioVerificationResult",
    "ConcurrentRevisionError",
    "ConceptNotFoundError",
    "ConceptNotPinnedError",
    "CreateRecordingCommand",
    "DatabaseUnavailableError",
    "DuplicateAnnotationError",
    "FileRecoveryOutbox",
    "GeometryNotAllowedError",
    "GeometryOutOfBoundsError",
    "InvalidAnnotationAttributesError",
    "InvalidRecoveryEnvelopeError",
    "LibraryHandler",
    "LibraryNotFoundError",
    "LibraryStore",
    "LibraryVersionInUseError",
    "LibraryVersionNotFoundError",
    "LocalAudioStorage",
    "PendingRecoveryOperationError",
    "PendingSave",
    "PersistenceError",
    "PersistenceIntegrityError",
    "PersistenceStore",
    "Queued",
    "RecordingEditSession",
    "RecordingHandler",
    "RecordingNotFoundError",
    "RecordingRevisionSummary",
    "RecordingStore",
    "RecordingSummary",
    "RecordingWorkspace",
    "RecoveryApplied",
    "RecoveryConflict",
    "RecoveryEnvelope",
    "RecoveryHandler",
    "RecoveryOutbox",
    "RecoveryResult",
    "RecoveryStorageError",
    "ResolvedAudio",
    "RevisionNotFoundError",
    "SaveConflict",
    "SaveResult",
    "Saved",
    "SpeakerHandler",
    "SpeakerNotFoundError",
    "SpeakerStore",
    "SyncState",
    "UnsupportedAudioError",
    "WorkbenchAPI",
    "WorkbenchError",
    "create_workbench",
    "library_content_sha256",
]
